version: '3'

services:
  db:
    image: m.daocloud.io/docker.io/library/postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lianruiying
      - POSTGRES_PASSWORD=LOLOLOLOL
      - POSTGRES_DB=language_tutor
    ports:
      - "5433:5432"
    restart: always
    networks:
      - my_custom_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=lianruiying
      - POSTGRES_PASSWORD=LOLOLOLOL
      - POSTGRES_DB=language_tutor
      - POSTGRES_PORT=5432
      - SECRET_KEY=0ab283a0598774c0ecf2380ae2ef04964ca5c75148afb01011f97ec2cc8c44ca
      - DEEPSEEK_API_KEY=sk-f1df6c6564944fac9e50907f610187e2
    restart: always
    networks:
      - my_custom_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - my_custom_network

volumes:
  postgres_data:
networks:
  my_custom_network:
    external: true
