services:
  db:
    image: m.daocloud.io/docker.io/library/postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lianruiying
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=language_tutor
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./language_tutor/backend:/app/language_tutor/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_SERVER=114.55.128.59
      - POSTGRES_USER=lianruiying
      - POSTGRES_PASSWORD=LOLOLOLOL
      - POSTGRES_DB=language_tutor
      - POSTGRES_PORT=5432
      - SECRET_KEY=0ab283a0598774c0ecf2380ae2ef04964ca5c75148afb01011f97ec2cc8c44ca
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./language_tutor/frontend:/app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: